#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: registry.guck.se/gitom
  # -- image tag
  tag: 1.0.0
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [gitom documentation](https://gitom.org/docs).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

git:
  # List of public ssh keys which are authorized to access the repositories
  authorizedKeys:
  # Name of default branch when initializing new repositories
  defaultBranch: master
  # List of git repositories to create
  repositories:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      ssh:
        enabled: true
        port: 22

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  repo:
    enabled: false
    accessMode: ReadWriteOnce
    size: 1Gi
