{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "gitom.harcodedValues" -}}
controller:
  type: statefulset

env:
  DEFAULT_BRANCH: {{ .Values.git.defaultBranch | default "master" | quote }}
  REPOSITORIES: "{{- join " " .Values.git.repositories }}"

ingress:
  main:
    enabled: false

# TODO: Add support for probes
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

persistence:
  repo:
    mountPath: /git
  hostkeys:
    enabled: true
    type: secret
    name: {{ include "common.names.fullname" . }}-hostkeys
    defaultMode: 0600
  authorizedkeys:
    enabled: true
    type: configMap
    name: {{ include "common.names.fullname" . }}-authorized-keys

service:
  main:
    ports:
      http:
        enabled: false

{{- end -}}
{{- $_ := mergeOverwrite .Values (include "gitom.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
