{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "gitom.harcodedValues" -}}
controller:
  type: statefulset

ingress:
  main:
    enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

persistence:
  repo:
    mountPath: /git

{{- end -}}
{{- $_ := mergeOverwrite .Values (include "gitom.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
