apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-hostkey-job
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-50"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "common.names.fullname" . }}-hostkey-job
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: hostkey-initializer
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOSTKEY_SECRET
              value: {{ include "common.names.fullname" . }}-hostkeys
          command: ["sh", "-c", "/keygen.sh"]
